# This is a basic workflow to help you get started with Actions

name: generate-readme

# Controls when the workflow will run
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 0 * * *'
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: golang:1.16.10-bullseye

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: generate-readme
        run: |
          cd "$GITHUB_WORKSPACE/generator"
          go build main.go
          mv main "$GITHUB_WORKSPACE"
          cd "$GITHUB_WORKSPACE"
          apt-get update && apt-get install -y fortune-mod
          FORTUNE=$(/usr/games/fortune) ./main
          git config --global user.name Robbie
          git config --global user.email rlankfo@gmail.com
          git add README.md
          git commit -m'ci: generate README.md'
          git push origin main
